from django.urls import path
from . import views

urlpatterns = [
    path('stats/',                     views.StatsView.as_view()),
    path('leads/',                     views.LeadListView.as_view()),
    path('leads/bulk-delete/',         views.BulkDeleteLeadsView.as_view()),
    path('leads/import/',              views.BulkImportLeadsView.as_view()),
    path('leads/import-template/',     views.LeadImportTemplateView.as_view()),
    path('leads/<int:pk>/',            views.LeadDetailView.as_view()),
    path('projects/',                  views.ProjectListView.as_view()),
    path('projects/<int:pk>/',         views.ProjectDetailView.as_view()),
    path('leads/backfill-duplicates/', views.BackfillDuplicatesView.as_view()),
    path('sources/',                   views.LeadSourceListView.as_view()),
    path('sources/<int:pk>/',          views.LeadSourceDetailView.as_view()),
    path('follow-ups/',                views.FollowUpListView.as_view()),
    path('follow-ups/<int:pk>/',       views.FollowUpDetailView.as_view()),
    path('site-visits/',               views.SiteVisitListView.as_view()),
    path('site-visits/<int:pk>/',      views.SiteVisitDetailView.as_view()),
    path('closures/',                  views.ClosureListView.as_view()),
    path('closures/<int:pk>/cancel/',  views.ClosureCancelView.as_view()),
    path('bookings/',                  views.BookingListCreateView.as_view()),
    path('bookings/<int:pk>/action/',  views.BookingActionView.as_view()),
    path('users/telecallers/',         views.TelecallerListView.as_view()),
    path('users/slim/',                views.CompanyUsersSlimView.as_view()),
    path('team/',                      views.SalesTeamView.as_view()),
    path('team/<int:pk>/',             views.SalesTeamMemberDetailView.as_view()),
    path('distribute/',                views.DistributeView.as_view()),
    path('distribution-log/',          views.DistributionLogView.as_view()),
    path('dist-settings/',             views.DistributionSettingsView.as_view()),
    path('availability/',              views.AvailabilityView.as_view()),
    path('availability/me/',           views.MyAvailabilityView.as_view()),
    path('dist-weight/',               views.DistributionWeightView.as_view()),
    path('reports/',                   views.ReportsView.as_view()),
    path('my-team/',                   views.MyTeamView.as_view()),
    path('plots/',                     views.PlotListView.as_view()),
    path('plots/bulk/',                views.PlotBulkCreateView.as_view()),
    path('plots/bulk-delete/',         views.PlotBulkDeleteView.as_view()),
    path('plots/rename-type/',         views.PlotRenameTypeView.as_view()),
    path('plots/<int:pk>/',            views.PlotDetailView.as_view()),
    path('webhooks/meta/',             views.MetaWebhookView.as_view()),
    path('webhooks/meta/config/',      views.MetaWebhookConfigView.as_view()),
    path('webhooks/meta/mappings/',    views.MetaFormMappingView.as_view()),
    path('user-projects/',             views.UserProjectAssignmentView.as_view()),
]
