[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn vistararealtybackend.wsgi --bind 0.0.0.0:$PORT --log-file -"
