# Generated by Django 4.2.30 on 2026-06-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
        ('inventory', '0001_initial'),
        ('erp_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('match_status', models.CharField(choices=[('Pending', 'Pending'), ('2-Way', '2-Way Matched'), ('3-Way', '3-Way Matched'), ('Approved', 'Approved'), ('Disputed', 'Disputed')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchase.poheader')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_invoices', to='erp_master.erpproject')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp_master.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_mode', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('UPI', 'UPI')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.vendorinvoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp_master.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('billed_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('rate_match', models.BooleanField(default=False)),
                ('qty_match', models.BooleanField(default=False)),
                ('match_note', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity')),
                ('grn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.grnline')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.vendorinvoice')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.poline')),
            ],
            options={
                'indexes': [models.Index(fields=['activity'], name='finance_ven_activit_00d0cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['project', 'match_status'], name='finance_ven_project_adc123_idx'),
        ),
    ]
