# Generated by Django 4.2.30 on 2026-06-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0001_initial'),
        ('erp_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('po_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Dispatched', 'Dispatched'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('payment_terms', models.PositiveIntegerField(default=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp_master.erpproject')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='erp_master.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('uom', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.poheader')),
                ('pr_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='execution.prline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.erpproject')),
            ],
            options={
                'indexes': [models.Index(fields=['activity'], name='purchase_po_activit_6a6838_idx'), models.Index(fields=['project'], name='purchase_po_project_934dd8_idx'), models.Index(fields=['pr_line'], name='purchase_po_pr_line_bfdf42_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['project', 'status'], name='purchase_po_project_a0ac3c_idx'),
        ),
    ]
