# Generated by Django 4.2.30 on 2026-08-18 05:52

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_admin_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
    ]
