# Generated by Django 4.2.30 on 2026-08-21 11:46

from django.db import migrations, models
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=sales.fields.EncryptedTextField(),
        ),
    ]
