# Generated by Django 4.2.30 on 2026-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_email_key_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export_bookings',
            field=models.BooleanField(default=False),
        ),
    ]
