# Generated by Django 4.2.30 on 2026-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_can_export_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designation',
            name='capabilities_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='data_scope',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='denied_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
