# Generated by Django 4.2.30 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_seed_designation_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='dashboard',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='designation',
            name='screens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designation',
            name='screens_set',
            field=models.BooleanField(default=False),
        ),
    ]
