# Generated by Django 4.2.30 on 2026-09-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
        ('accounts', '0016_seed_cp_screens'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=40)),
                ('view', models.CharField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_dashboards', to='companies.company')),
            ],
            options={
                'ordering': ['module', 'role'],
                'unique_together': {('company', 'module', 'role')},
            },
        ),
    ]
