# Generated by Django 4.2.30 on 2026-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_designation_screen_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='dashboard',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
