# Generated by Django 4.2.30 on 2026-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_designation_dashboard_longer_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export_leads',
            field=models.BooleanField(default=False),
        ),
    ]
