# Generated by Django 4.2.30 on 2026-10-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_can_export_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_ai',
            field=models.BooleanField(default=False),
        ),
    ]
