# Generated by Django 4.2.30 on 2026-06-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
        ('erp_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('received_date', models.DateField()),
                ('dc_no', models.CharField(blank=True, max_length=50)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Pending QC', 'Pending QC'), ('QC Passed', 'QC Passed'), ('QC Failed', 'QC Failed'), ('Stocked', 'Stocked')], default='Pending QC', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchase.poheader')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='erp_master.erpproject')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns_received', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='erp_master.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('GRN_IN', 'GRN Receipt'), ('ISSUE_OUT', 'Issue to Site'), ('RETURN_IN', 'Return from Site'), ('REJECT_OUT', 'QC Rejection'), ('ADJ_IN', 'Adjustment In'), ('ADJ_OUT', 'Adjustment Out')], max_length=20)),
                ('ref_doc_type', models.CharField(max_length=20)),
                ('ref_doc_no', models.CharField(max_length=25)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('txn_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='erp_master.erpproject')),
            ],
            options={
                'ordering': ['-txn_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'item_code'], name='inventory_s_project_6a5899_idx')],
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_accepted', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_rejected', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('uom', models.CharField(max_length=20)),
                ('qc_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('qc_remarks', models.TextField(blank=True)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.grnheader')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='purchase.poline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.erpproject')),
            ],
            options={
                'indexes': [models.Index(fields=['activity'], name='inventory_g_activit_6a38f0_idx'), models.Index(fields=['project'], name='inventory_g_project_654dfa_idx'), models.Index(fields=['po_line'], name='inventory_g_po_line_92bfd3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grnheader',
            index=models.Index(fields=['project', 'status'], name='inventory_g_project_a6a60f_idx'),
        ),
    ]
