# Generated by Django 4.2.30 on 2026-07-18 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sales.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('amount_invested', sales.fields.EncryptedDecimalField(decimal_places=2, max_digits=14)),
                ('investment_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('redeemed', 'Redeemed'), ('premature_redeemed', 'Premature Redeemed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club1000_investors_added', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club1000_investors', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenure_months', models.PositiveIntegerField()),
                ('fixed_return_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loyalty_benefit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_return_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_ticket_size', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_payout', models.CharField(choices=[('quarterly', 'Quarterly'), ('maturity', 'Maturity')], default='maturity', max_length=20)),
                ('principal_payout', models.CharField(choices=[('maturity', 'Maturity')], default='maturity', max_length=20)),
                ('premature_redemption_allowed', models.BooleanField(default=False)),
                ('premature_redemption_lock_months', models.PositiveIntegerField(blank=True, null=True)),
                ('premature_redemption_rate_pct_per_month', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club1000_schemes', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('interest', 'Interest'), ('maturity', 'Maturity'), ('premature_redemption', 'Premature Redemption')], max_length=25)),
                ('due_date', models.DateField()),
                ('amount_due', sales.fields.EncryptedDecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='club1000.investor')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investors', to='club1000.scheme'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['company', '-created_at'], name='club1000_inv_company_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['added_by'], name='club1000_inv_addedby_idx'),
        ),
    ]
