# Generated by Django 4.2.30 on 2026-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0002_investor_document_url_reference_investor_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='document_url',
        ),
        migrations.AddField(
            model_name='investor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='club1000/'),
        ),
    ]
