# Generated by Django 4.2.30 on 2026-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0003_remove_investor_document_url_investor_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='interest_payout',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('maturity', 'Maturity')], default='maturity', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='total_return_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
