# Generated by Django 4.2.30 on 2026-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0004_investor_interest_payout_investor_total_return_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='reference',
        ),
        migrations.AddField(
            model_name='investor',
            name='reference_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='investor',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
