# Generated by Django 4.2.30 on 2026-07-18 17:44

from django.db import migrations, models


def copy_interest_payout_to_options(apps, schema_editor):
    Scheme = apps.get_model('club1000', 'Scheme')
    for scheme in Scheme.objects.all():
        scheme.interest_payout_options = [scheme.interest_payout] if scheme.interest_payout else ['maturity']
        scheme.save(update_fields=['interest_payout_options'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0005_remove_investor_reference_investor_reference_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='interest_payout_options',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(copy_interest_payout_to_options, noop),
        migrations.RemoveField(
            model_name='scheme',
            name='interest_payout',
        ),
    ]
