# Generated by Django 4.2.30 on 2026-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0008_investor_loi_document_investor_loi_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
