# Generated by Django 4.2.30 on 2026-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0009_lead_next_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='investor_approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
