# Generated by Django 4.2.30 on 2026-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0010_investor_approval_status_scheme_investor_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='pending_payout_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
