# Generated by Django 4.2.30 on 2026-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0011_investor_pending_payout_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='total_return_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
