# Generated by Django 4.2.30 on 2026-07-29 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0012_lead_total_return_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
