# Generated by Django 4.2.30 on 2026-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0013_lead_lead_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='outcome',
            field=models.TextField(blank=True),
        ),
    ]
