# Generated by Django 4.2.30 on 2026-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0015_leadstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='pending_loi_document',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='investor',
            name='pending_revision',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='revision_no',
            field=models.IntegerField(default=0),
        ),
    ]
