# Generated by Django 4.2.30 on 2026-07-31 07:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0016_investor_pending_loi_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='pending_revision_type',
            field=models.CharField(choices=[('revise', 'Revise'), ('renew', 'Renew')], default='revise', max_length=10),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='club1000.investor'),
        ),
    ]
