# Generated by Django 4.2.30 on 2026-07-31 17:44

from django.db import migrations, models


def seed_payout_rates(apps, schema_editor):
    """Replicate each scheme's old flat total_return_pct across every
    currently-enabled frequency, so existing schemes/investors see no change
    in behavior until an admin actually differentiates the per-frequency rates."""
    Scheme = apps.get_model('club1000', 'Scheme')
    for scheme in Scheme.objects.all():
        rate = str(scheme.total_return_pct) if scheme.total_return_pct is not None else '0'
        scheme.payout_rates = {freq: rate for freq in (scheme.interest_payout_options or [])}
        scheme.save(update_fields=['payout_rates'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0017_investor_pending_revision_type_referralreward_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='payout_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_payout_rates, noop),
        migrations.RemoveField(
            model_name='scheme',
            name='fixed_return_pct',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='loyalty_benefit_pct',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='total_return_pct',
        ),
    ]
