# Generated by Django 4.2.30 on 2026-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0018_remove_scheme_fixed_return_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='source',
            field=models.CharField(choices=[('referral', 'Referral'), ('walk_in', 'Walk-in'), ('website', 'Website'), ('other', 'Other')], default='referral', max_length=20),
        ),
    ]
