# Generated by Django 4.2.30 on 2026-08-18 05:53

from django.db import migrations, models
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0019_investor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='followup',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=sales.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='investor',
            name='notes',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='pan',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=sales.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='investor',
            name='reference_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='reference_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='alt_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=sales.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=sales.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reference_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reference_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='notes',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reference_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reference_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
    ]
