# Generated by Django 4.2.30 on 2026-08-19 11:40

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0020_investor_phone_key_lead_phone_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paid_amount',
            field=sales.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
