# Generated by Django 4.2.30 on 2026-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club1000', '0021_payout_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
