# Generated by Django 4.2.30 on 2026-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('company', 'code'), name='uniq_task_code_per_company'),
        ),
    ]
