# Generated by Django 4.2.30 on 2026-09-22 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', sales.fields.EncryptedTextField(blank=True)),
                ('module', models.CharField(db_index=True, max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('summary', sales.fields.EncryptedTextField(blank=True)),
                ('details', sales.fields.EncryptedTextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip', sales.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='activity_ac_company_a12d03_idx'), models.Index(fields=['target_type', 'target_id'], name='activity_ac_target__16e969_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ac_actor_i_3a6bb7_idx')],
            },
        ),
    ]
