# Generated by Django 4.2.30 on 2026-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='loi_enabled',
            field=models.BooleanField(default=False, help_text='Allow this company to generate and open LOI / EOI documents.'),
        ),
    ]
