# Generated by Django 4.2.30 on 2026-08-18 05:53

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_enable_loi_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
    ]
