# Generated by Django 4.2.30 on 2026-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project_approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
