# Generated by Django 4.2.30 on 2026-06-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssueHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('issued_date', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_issued', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('uom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('mb_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Certified', 'Certified'), ('Billed', 'Billed')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mbs_certified', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mbs_prepared', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_books', to='erp_master.erpproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Raised', 'Raised'), ('Approved', 'Approved'), ('PO Created', 'PO Created'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Issued to Site', 'Issued to Site'), ('Closed', 'Closed')], default='Raised', max_length=30)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='erp_master.erpproject')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prs_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RABill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_bill_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Certified', 'Certified'), ('Invoiced', 'Invoiced'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ra_bills', to='execution.measurementbook')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ra_bills', to='erp_master.erpproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_required', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_on_po', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('uom', models.CharField(max_length=20)),
                ('required_date', models.DateField()),
                ('status', models.CharField(choices=[('Raised', 'Raised'), ('Approved', 'Approved'), ('PO Created', 'PO Created'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Issued to Site', 'Issued to Site'), ('Closed', 'Closed')], default='Raised', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='execution.prheader')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.erpproject')),
            ],
        ),
        migrations.CreateModel(
            name='MBLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('qty_executed', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity')),
                ('mb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='execution.measurementbook')),
            ],
        ),
    ]
