# Generated by Django 4.2.30 on 2026-06-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0001_initial'),
        ('inventory', '0001_initial'),
        ('erp_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueline',
            name='grn_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.grnline'),
        ),
        migrations.AddField(
            model_name='materialissueline',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='execution.materialissueheader'),
        ),
        migrations.AddField(
            model_name='materialissueline',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.material'),
        ),
        migrations.AddField(
            model_name='materialissueheader',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_master.wbsactivity'),
        ),
        migrations.AddField(
            model_name='materialissueheader',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissueheader',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='erp_master.erpproject'),
        ),
        migrations.AddIndex(
            model_name='prline',
            index=models.Index(fields=['activity'], name='execution_p_activit_6923a4_idx'),
        ),
        migrations.AddIndex(
            model_name='prline',
            index=models.Index(fields=['project'], name='execution_p_project_bc6bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='prheader',
            index=models.Index(fields=['project', 'status'], name='execution_p_project_374fad_idx'),
        ),
        migrations.AddIndex(
            model_name='materialissueheader',
            index=models.Index(fields=['project', 'activity'], name='execution_m_project_9f67b2_idx'),
        ),
    ]
