# Generated by Django 4.2.29 on 2026-05-15 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('leave', 'Leave'), ('wfh', 'WFH')], default='leave', max_length=10)),
                ('leave_type', models.CharField(choices=[('paid_leave', 'Paid Leave'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('lop', 'LOP')], max_length=20)),
                ('day_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=10)),
                ('session', models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
    ]
