# Generated by Django 4.2.29 on 2026-05-16 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('leave_type', models.CharField(choices=[('paid_leave', 'Paid Leave'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('lop', 'LOP')], default='paid_leave', max_length=20)),
                ('description', models.CharField(choices=[('monthly_credit', 'Monthly Credit'), ('leave_applied', 'Leave Applied'), ('manual_credit', 'Manual Credit'), ('manual_debit', 'Manual Debit')], max_length=30)),
                ('change', models.DecimalField(decimal_places=1, max_digits=5)),
                ('balance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
