# Generated by Django 4.2.29 on 2026-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leavetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetransaction',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
