# Generated by Django 4.2.30 on 2026-09-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0084_list_endpoint_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', max_length=10)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('legal_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_accounts', to='sales.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_accounts', to='companies.company')),
                ('root_booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ar_account_root', to='sales.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ARReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('amount', sales.fields.EncryptedDecimalField(decimal_places=2, max_digits=16)),
                ('mode', models.CharField(choices=[('bank', 'Bank'), ('nbfc', 'NBFC'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=10)),
                ('remarks', sales.fields.EncryptedTextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Entered'), ('import', 'Excel import')], default='manual', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receivables.araccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paid_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ARReceiptAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('delete', 'Deleted')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('before', sales.fields.EncryptedTextField(blank=True)),
                ('after', sales.fields.EncryptedTextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='receivables.arreceipt')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['account', 'is_deleted', 'paid_on'], name='receivables_account_34d321_idx'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['company', 'status'], name='receivables_company_aa898a_idx'),
        ),
    ]
