# Generated by Django 4.2.30 on 2026-09-21 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='araccount',
            name='schedule',
            field=sales.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='araccount',
            name='schedule_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='araccount',
            name='schedule_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
