# Generated by Django 4.2.30 on 2026-09-21 12:16

from django.db import migrations, models
import sales.fields


def encrypt_existing(apps, schema_editor):
    """Columns just changed to encrypted types still hold plaintext; re-saving
    each row writes it back as ciphertext (reads accept either, so this is safe
    to re-run)."""
    ARReceipt = apps.get_model('receivables', 'ARReceipt')
    ARAccount = apps.get_model('receivables', 'ARAccount')
    for r in ARReceipt.objects.all():
        r.save(update_fields=['paid_on', 'mode'])
    for a in ARAccount.objects.exclude(legal_due_date__isnull=True):
        a.save(update_fields=['legal_due_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_ar_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arreceipt',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='receivables_account_34d321_idx',
        ),
        migrations.AlterField(
            model_name='araccount',
            name='legal_due_date',
            field=sales.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arreceipt',
            name='mode',
            field=sales.fields.EncryptedTextField(choices=[('bank', 'Bank'), ('nbfc', 'NBFC'), ('cash', 'Cash'), ('cheque', 'Cheque')]),
        ),
        migrations.AlterField(
            model_name='arreceipt',
            name='paid_on',
            field=sales.fields.EncryptedDateField(),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['account', 'is_deleted'], name='receivables_account_e2a46d_idx'),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
