# Generated by Django 4.2.30 on 2026-09-22 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receivables', '0003_encrypt_dates_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('visit', 'Visit'), ('email', 'Email'), ('other', 'Other')], default='call', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('note', sales.fields.EncryptedTextField(blank=True)),
                ('outcome', sales.fields.EncryptedTextField(blank=True)),
                ('promised_amount', sales.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('promised_on', sales.fields.EncryptedDateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='receivables.araccount')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='receivables_status_6cfdde_idx'), models.Index(fields=['account', 'status'], name='receivables_account_181b6e_idx')],
            },
        ),
    ]
