# Generated by Django 4.2.30 on 2026-10-02 04:53

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_ar_followups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arreceipt',
            name='mode',
            field=sales.fields.EncryptedTextField(choices=[('loan', 'Loan'), ('nbfc', 'NBFC'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')]),
        ),
    ]
