# Generated by Django 4.2.30 on 2026-10-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_project_approvers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receivables', '0005_receipt_mode_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', sales.fields.EncryptedTextField()),
                ('account_no', sales.fields.EncryptedTextField(blank=True, default='')),
                ('opening_balance', sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_banks', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arreceipt',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receivables.arbank'),
        ),
        migrations.AddIndex(
            model_name='arbank',
            index=models.Index(fields=['company', 'is_active'], name='receivables_company_197fd4_idx'),
        ),
    ]
