# Generated by Django 4.2.30 on 2026-10-02 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_project_approvers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0094_project_approval_status_project_approved_at_and_more'),
        ('receivables', '0006_arbank_arreceipt_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', sales.fields.EncryptedTextField(blank=True, default='')),
                ('deal_net', sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16)),
                ('forfeit_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('forfeit', sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16)),
                ('received', sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16)),
                ('refund_due', sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', sales.fields.EncryptedTextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='receivables.araccount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_cancellations', to='sales.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_cancellations', to='companies.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ARRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', sales.fields.EncryptedDateField()),
                ('amount', sales.fields.EncryptedDecimalField(decimal_places=2, max_digits=16)),
                ('reference', sales.fields.EncryptedTextField(blank=True, default='')),
                ('remarks', sales.fields.EncryptedTextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='receivables.arbank')),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='receivables.arcancellation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='arcancellation',
            index=models.Index(fields=['company', 'status'], name='receivables_company_a12c05_idx'),
        ),
    ]
