# Generated by Django 4.2.29 on 2026-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_followup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
