# Generated by Django 4.2.30 on 2026-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesteammember_distributionlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='sales_lead_status_54f721_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telecaller_status'], name='sales_lead_telecal_eac450_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stm_status'], name='sales_lead_stm_sta_981631_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project'], name='sales_lead_project_9edd01_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telecaller'], name='sales_lead_telecal_d7f7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stm'], name='sales_lead_stm_id_0f0634_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='sales_lead_created_0feb90_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_duplicate'], name='sales_lead_is_dupl_da9e51_idx'),
        ),
    ]
