# Generated by Django 4.2.30 on 2026-06-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_userdistributionweight_distributionsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='possession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='price_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='rera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='total_plots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('sold', 'Sold')], default='available', max_length=20)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('cluster_type', models.CharField(blank=True, max_length=100)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='sales.project')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('project', 'number')},
            },
        ),
    ]
