# Generated by Django 4.2.30 on 2026-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_project_fields_and_plot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_map_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='site_map_zones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
