# Generated by Django 4.2.30 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_sitemap_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
