# Generated by Django 4.2.30 on 2026-06-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_plot_number_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_token', models.CharField(max_length=200)),
                ('page_access_token', models.CharField(blank=True, max_length=600)),
                ('is_active', models.BooleanField(default=False)),
                ('total_leads_received', models.IntegerField(default=0)),
                ('last_lead_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.project')),
            ],
        ),
    ]
