# Generated by Django 4.2.30 on 2026-06-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_meta_webhook_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFormMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('form_name', models.CharField(blank=True, max_length=200)),
                ('total_leads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_form_mappings', to='sales.project')),
            ],
        ),
    ]
