# Generated by Django 4.2.30 on 2026-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_meta_form_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='metawebhookconfig',
            name='subscribed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
