# Generated by Django 4.2.30 on 2026-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_add_subscribed_pages_to_meta_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='metawebhookconfig',
            name='pages_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
