# Generated by Django 4.2.30 on 2026-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_pages_data_to_meta_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='metawebhookconfig',
            name='pages_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
