# Generated by Django 4.2.30 on 2026-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_pages_refreshed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_adset_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
