# Generated by Django 4.2.30 on 2026-06-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('sales', '0015_add_user_project_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_logs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='companies.company'),
        ),
        migrations.AddField(
            model_name='metaformmapping',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_form_mappings', to='companies.company'),
        ),
        migrations.AddField(
            model_name='metawebhookconfig',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_webhook_config', to='companies.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leadsource',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company'], name='sales_lead_company_0bd910_idx'),
        ),
    ]
