# Generated by Django 4.2.30 on 2026-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_reassign_mmda_to_vrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telecaller_status',
            field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('cold', 'Cold'), ('not_interested', 'Not Interested'), ('not_reachable', 'Not Reachable'), ('callback', 'Callback')], max_length=30),
        ),
    ]
