# Generated by Django 4.2.30 on 2026-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_lead_telecaller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('not_reachable', 'Not Reachable'), ('warm_transferred', 'Warm Transferred'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('not_interested', 'Not Interested'), ('sv_scheduled', 'SV Scheduled'), ('sv_done', 'SV Done'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=30),
        ),
    ]
