# Generated by Django 4.2.30 on 2026-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_lead_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to', 'scheduled_at'], name='followup_assignee_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead'], name='followup_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', '-created_at'], name='lead_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telecaller', 'telecaller_status', '-created_at'], name='lead_tc_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stm', 'stm_status', '-created_at'], name='lead_stm_status_created_idx'),
        ),
    ]
