# Generated by Django 4.2.30 on 2026-06-21 05:49

from django.db import migrations
import sales.fields


def encrypt_tokens(apps, schema_editor):
    """Encrypt any existing plaintext page_access_token values in place.

    Uses raw SQL so the field's auto-encryption isn't applied twice. No-op when
    FIELD_ENCRYPTION_KEY is unset (values stay plaintext; the field passes through)
    and idempotent (skips rows that are already valid Fernet ciphertext).
    """
    f = sales.fields.get_fernet()
    if f is None:
        return
    from cryptography.fernet import InvalidToken
    conn = schema_editor.connection
    with conn.cursor() as cur:
        cur.execute("SELECT id, page_access_token FROM sales_metawebhookconfig WHERE page_access_token <> ''")
        rows = cur.fetchall()
        for pk, val in rows:
            if not val:
                continue
            try:
                f.decrypt(val.encode())
                continue  # already encrypted
            except (InvalidToken, Exception):
                pass
            enc = f.encrypt(val.encode()).decode()
            cur.execute(
                "UPDATE sales_metawebhookconfig SET page_access_token = %s WHERE id = %s",
                [enc, pk],
            )


def decrypt_tokens(apps, schema_editor):
    """Reverse: decrypt back to plaintext (best-effort)."""
    f = sales.fields.get_fernet()
    if f is None:
        return
    from cryptography.fernet import InvalidToken
    conn = schema_editor.connection
    with conn.cursor() as cur:
        cur.execute("SELECT id, page_access_token FROM sales_metawebhookconfig WHERE page_access_token <> ''")
        for pk, val in cur.fetchall():
            if not val:
                continue
            try:
                dec = f.decrypt(val.encode()).decode()
            except (InvalidToken, Exception):
                continue  # already plaintext
            cur.execute(
                "UPDATE sales_metawebhookconfig SET page_access_token = %s WHERE id = %s",
                [dec, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_followup_followup_assignee_sched_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metawebhookconfig',
            name='page_access_token',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_tokens, decrypt_tokens),
    ]
