# Generated by Django 4.2.30 on 2026-06-23 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0022_alter_metawebhookconfig_page_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_unit_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='formula_set',
            field=models.CharField(choices=[('kalrav', 'Kalrav'), ('ankhol', 'Ankhol'), ('industrial', 'Industrial')], default='kalrav', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('formula_set', models.CharField(default='kalrav', max_length=20)),
                ('area', models.CharField(blank=True, max_length=30)),
                ('area_unit', models.CharField(default='sq.yd', max_length=10)),
                ('const_area', models.CharField(blank=True, max_length=30)),
                ('villa_type', models.CharField(blank=True, max_length=50)),
                ('bunglow_type', models.CharField(blank=True, max_length=50)),
                ('land_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dev_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('const_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_deed_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dev_agreement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maint_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maint_months', models.IntegerField(default=0)),
                ('plot_basic', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('plot_dev', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('const_amt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sale_deed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dev_agreement', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('land_sale_deed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('const_agreement', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reg_fees', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maint_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maint_advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('legal_charges', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('premium_location', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_extra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('apply_reg_fee', models.CharField(default='Yes', max_length=5)),
                ('apply_stamp_duty', models.CharField(default='Yes', max_length=5)),
                ('apply_gst', models.CharField(default='Yes', max_length=5)),
                ('installments', models.JSONField(blank=True, default=list)),
                ('extra_work_desc', models.CharField(blank=True, max_length=300)),
                ('extra_work_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('extra_work_inst', models.JSONField(blank=True, default=list)),
                ('extra_terms', models.JSONField(blank=True, default=list)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('cp_name', models.CharField(blank=True, max_length=200)),
                ('loi_document', models.FileField(blank=True, null=True, upload_to='loi/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='pending', max_length=20)),
                ('approval_status', models.CharField(blank=True, max_length=40)),
                ('revision_no', models.IntegerField(default=0)),
                ('pending_revision', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sales.closure')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sales.lead')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sales.plot')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sales.project')),
                ('stm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
