# Generated by Django 4.2.30 on 2026-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_project_allow_unit_switch_project_formula_set_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='approver_email',
                    field=models.EmailField(blank=True, default='', max_length=254),
                ),
            ],
            # Column already exists in the database — no ALTER TABLE needed.
            database_operations=[],
        ),
    ]
