# Generated by Django 4.2.30 on 2026-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_project_approver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsettings',
            name='booking_approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
