# Generated by Django 4.2.30 on 2026-06-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_distributionsettings_booking_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='booking_approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
