# Generated by Django 4.2.30 on 2026-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_project_booking_approvers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='loi_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
