# Generated by Django 4.2.30 on 2026-06-25 06:55

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_set_industrial_pricing_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='const_agreement',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='const_amt',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='const_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dev_agreement',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dev_agreement_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dev_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_work_amount',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='final_amount',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gst',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='land_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='land_sale_deed',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='legal_charges',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maint_advance',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maint_deposit',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maint_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maintenance',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='plot_basic',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='plot_dev',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='premium_location',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reg_fees',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sale_deed',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sale_deed_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stamp_duty',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_extra',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='closure',
            name='booking_amount',
            field=sales.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='total_amount',
            field=sales.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
