# Generated by Django 4.2.30 on 2026-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_encrypt_money_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
