# Generated by Django 4.2.30 on 2026-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_followup_escalated_at_followup_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_bucket',
            field=models.CharField(blank=True, choices=[('lt_10l', 'Less than ₹10 Lakh'), ('10_50l', '₹10 – 50 Lakh'), ('50l_1cr', '₹50 Lakh – ₹1 Cr'), ('1_2cr', '₹1 – 2 Cr'), ('2_3cr', '₹2 – 3 Cr'), ('3_5cr', '₹3 – 5 Cr'), ('gt_5cr', 'Above ₹5 Cr')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='purpose',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
