# Generated by Django 4.2.30 on 2026-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_lead_address_lead_budget_bucket_lead_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plot_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='plot_numbers',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
