# Generated by Django 4.2.30 on 2026-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_booking_plot_ids_booking_plot_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_form_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
