# Generated by Django 4.2.30 on 2026-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_project_eoi_unit_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='loi_document',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
