# Generated by Django 4.2.30 on 2026-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_alter_booking_loi_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kiosk_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
