# Generated by Django 4.2.30 on 2026-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_rebuild_orphaned_booking_closures'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='terrace_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
