# Generated by Django 4.2.30 on 2026-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_tower_floor_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floor_wise',
            field=models.BooleanField(default=False),
        ),
    ]
