# Generated by Django 4.2.30 on 2026-08-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_project_floor_wise'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='price_book',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='formula_set',
            field=models.CharField(choices=[('kalrav', 'Kalrav'), ('ankhol', 'Ankhol'), ('industrial', 'Industrial'), ('pratishtha', 'Pratishtha')], default='kalrav', max_length=20),
        ),
    ]
