# Generated by Django 4.2.30 on 2026-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_plot_price_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_stm_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
