# Generated by Django 4.2.30 on 2026-08-07 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0051_booking_manual_stm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_plots', to=settings.AUTH_USER_MODEL),
        ),
    ]
