# Generated by Django 4.2.30 on 2026-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_plot_held_at_plot_held_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='pending', max_length=20),
        ),
    ]
