# Generated by Django 4.2.30 on 2026-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block_industrial',
            field=models.BooleanField(default=False),
        ),
    ]
