# Generated by Django 4.2.30 on 2026-08-18 04:50

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_backupsettings_backuprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cp_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='manual_stm_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='client_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='client_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='alt_phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='meta_ad_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='meta_adset_name',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stm_remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telecaller_remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='notes',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='remarks',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
    ]
