# Generated by Django 4.2.30 on 2026-08-18 05:12

from django.db import migrations, models
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_alter_booking_address_alter_booking_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=sales.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=sales.fields.EncryptedTextField(),
        ),
    ]
