# Generated by Django 4.2.30 on 2026-08-18 05:16

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_lead_phone_key_alter_lead_email_alter_lead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metawebhookconfig',
            name='app_secret',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
    ]
