# Generated by Django 4.2.30 on 2026-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_metawebhookconfig_app_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loi_variant',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('tundav', 'Tundav'), ('kalrav3', 'Kalrav 3')], default='', max_length=30),
        ),
    ]
