# Generated by Django 4.2.30 on 2026-08-18 05:53

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_seed_loi_variant_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='approver_email',
            field=sales.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
