# Generated by Django 4.2.30 on 2026-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_alter_booking_phone_alter_project_approver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested')], max_length=20),
        ),
    ]
