# Generated by Django 4.2.30 on 2026-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_alter_booking_phone_alter_project_approver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skip_telecaller',
            field=models.BooleanField(default=False, help_text='No telecaller stage: assign new leads for this project directly to an STM.'),
        ),
    ]
