# Generated by Django 4.2.30 on 2026-08-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_project_skip_telecaller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skip_telecaller',
        ),
    ]
