# Generated by Django 4.2.30 on 2026-08-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_sitevisit_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=20),
        ),
    ]
