# Generated by Django 4.2.30 on 2026-08-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_alter_sitevisit_outcome'),
        ('sales', '0063_remove_project_skip_telecaller'),
    ]

    operations = [
    ]
