# Generated by Django 4.2.30 on 2026-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_alter_sitevisit_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('not_interested', 'Not Interested')], max_length=20),
        ),
    ]
