# Generated by Django 4.2.30 on 2026-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_alter_sitevisit_outcome'),
        ('sales', '0064_merge_20260820_1813'),
    ]

    operations = [
    ]
