# Generated by Django 4.2.30 on 2026-08-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_merge_20260820_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='sales.booking'),
        ),
    ]
