# Generated by Django 4.2.30 on 2026-08-22 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
        ('sales', '0067_backfill_revision_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', sales.fields.EncryptedTextField()),
                ('contact_no', sales.fields.EncryptedTextField()),
                ('contact_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('firm_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('premium', 'Premium'), ('normal', 'Normal'), ('referral', 'Referral')], default='normal', max_length=10)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partners', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='channel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.channelpartner'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['company'], name='sales_chann_company_9e3438_idx'),
        ),
    ]
