# Generated by Django 4.2.30 on 2026-08-22 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
        ('sales', '0067_backfill_revision_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', sales.fields.EncryptedTextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', sales.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_transfers', to='companies.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_transfers_decided', to=settings.AUTH_USER_MODEL)),
                ('from_stm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_transfers_out', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='sales.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_transfers', to='sales.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_stm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', '-created_at'], name='leadxfer_co_status_idx'), models.Index(fields=['lead'], name='leadxfer_lead_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='leadtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('lead',), name='one_pending_transfer_per_lead'),
        ),
    ]
