# Generated by Django 4.2.30 on 2026-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_channelpartner_lead_channel_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('industrial', 'Industrial'), ('both', 'Both')], max_length=15),
        ),
    ]
