# Generated by Django 4.2.30 on 2026-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_lead_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='segment',
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='segment',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('industrial', 'Industrial'), ('both', 'Both')], max_length=15),
        ),
    ]
