# Generated by Django 4.2.30 on 2026-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0070_remove_lead_segment_channelpartner_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
