# Generated by Django 4.2.30 on 2026-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_channelpartner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cp_booking_approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
