# Generated by Django 4.2.30 on 2026-08-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_leadtransfer_and_more'),
        ('sales', '0073_booking_approved_at'),
    ]

    operations = [
    ]
