# Generated by Django 4.2.30 on 2026-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0074_merge_20260825_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('sold', 'Sold'), ('resale', 'Resale')], default='available', max_length=20),
        ),
    ]
