# Generated by Django 4.2.30 on 2026-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_plot_resale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='pre_hold_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
