# Generated by Django 4.2.30 on 2026-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0076_plot_pre_hold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
