# Generated by Django 4.2.30 on 2026-09-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0077_channelpartner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate_master',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
