# Generated by Django 4.2.30 on 2026-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0078_project_rate_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailability',
            name='distribution_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
