# Generated by Django 4.2.30 on 2026-09-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0081_booking_decided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_resale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='resale_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resales', to='sales.booking'),
        ),
    ]
