# Generated by Django 4.2.30 on 2026-09-16 13:03

from django.db import migrations
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0082_booking_resale'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plc_rate',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
