# Generated by Django 4.2.30 on 2026-09-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0083_booking_plc_rate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'status'], name='sales_booki_company_e1c55c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='sales_booki_created_993694_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['-closure_date'], name='sales_closu_closure_6273cd_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['company', '-closure_date'], name='sales_closu_company_3c9b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['-scheduled_at'], name='sales_sitev_schedul_f69b02_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['status', '-scheduled_at'], name='sales_sitev_status_847808_idx'),
        ),
    ]
