# Generated by Django 4.2.30 on 2026-09-21 08:46

from django.db import migrations, models
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0084_list_endpoint_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='disqualify_note',
            field=sales.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='disqualify_reason',
            field=models.CharField(blank=True, choices=[('religion', 'Religion'), ('caste', 'Caste'), ('budget', 'Budget'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stm_status',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('not_interested', 'Not Interested'), ('sv_scheduled', 'SV Scheduled'), ('sv_done', 'SV Done'), ('closed', 'Closed'), ('not_qualified', 'Not Qualified')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telecaller_status',
            field=models.CharField(blank=True, choices=[('warm', 'Warm'), ('cold', 'Cold'), ('not_interested', 'Not Interested'), ('not_reachable', 'Not Reachable'), ('callback', 'Callback'), ('not_qualified', 'Not Qualified')], max_length=30),
        ),
    ]
