# Generated by Django 4.2.30 on 2026-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0085_lead_disqualify_note_lead_disqualify_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupsettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='BackupRecord',
        ),
        migrations.DeleteModel(
            name='BackupSettings',
        ),
    ]
