# Generated by Django 4.2.30 on 2026-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0087_backup_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupstamp',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
