# Generated by Django 4.2.30 on 2026-09-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_address_alter_company_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0088_backup_stamp_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupstamp',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupstamp',
            name='file_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='backupstamp',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('keep_last', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
