# Generated by Django 4.2.30 on 2026-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0089_backup_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='locked_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
