# Generated by Django 4.2.30 on 2026-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0090_project_is_locked_project_locked_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='manual_hold',
            field=models.BooleanField(default=False),
        ),
    ]
