# Generated by Django 4.2.30 on 2026-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0091_plot_manual_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='disqualify_reason',
            field=models.CharField(blank=True, choices=[('religion', 'Religion'), ('caste', 'Caste'), ('budget', 'Budget'), ('not_enquired', 'Not Enquired'), ('other', 'Other')], max_length=20),
        ),
    ]
