# Generated by Django 4.2.30 on 2026-09-30 05:08

from django.db import migrations, models
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0092_alter_lead_disqualify_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plc_clubhouse',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='plc_corner',
            field=sales.fields.EncryptedDecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_clubhouse_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_corner',
            field=models.BooleanField(default=False),
        ),
    ]
