# Generated by Django 4.2.30 on 2026-10-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0094_project_approval_status_project_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('remarks', sales.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='sales.channelpartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_site_visits', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_partner_visits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_site_visits', to='sales.project')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['channel_partner', '-scheduled_at'], name='sales_partn_channel_c5eab2_idx'), models.Index(fields=['project', 'status'], name='sales_partn_project_3e006d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('remarks', sales.fields.EncryptedTextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='sales.channelpartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['channel_partner', 'scheduled_at'], name='sales_partn_channel_0865a9_idx'), models.Index(fields=['assigned_to', 'status', 'scheduled_at'], name='sales_partn_assigne_a03911_idx')],
            },
        ),
    ]
