# Generated by Django 4.2.30 on 2026-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0095_partnersitevisit_partnerfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersitevisit',
            name='outcome',
            field=models.TextField(blank=True),
        ),
    ]
